name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Configure Environment
      run: |
        echo "export const environment = {" > src/environments/environment.prod.ts
        echo "  production: true," >> src/environments/environment.prod.ts
        echo "  tmdbApiKey: '${{ secrets.TMDB_API_KEY }}'," >> src/environments/environment.prod.ts
        echo "  kakaoApiKey: '${{ secrets.KAKAO_API_KEY }}'" >> src/environments/environment.prod.ts
        echo "};" >> src/environments/environment.prod.ts


    - name: Install dependencies and build Angular app
      run: |
        npm install
        npm run build --configuration=production --base-href=/netflix-clone/  # base-href 추가

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.ACTIONS_DEPLOY_KEY  }}
        branch: deploy
        folder: dist/browser  # 빌드된 Angular 앱 폴더

        
